package com.deluxedemo.deluxemodels;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Contact implements Serializable {

	static final long serialVersionUID = 1L;

	private String address;
	private String city;
	private String zipcode;

	public Contact() {
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public Contact(String address, String city,
			String zipcode) {
		this.address = address;
		this.city = city;
		this.zipcode = zipcode;
	}

}