package com.deluxedemo.deluxemodels;

import java.io.Serializable;

import java.util.Date;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer employeeId;
	private String name;
	private Date dateofHire;
	private String role;
	private String type;
	private String location;
	private Contact contact;

	private ComputerRequest requestedMachine;

	private ComputerRequest assignedMachine;

	private String emailAddress;

	private java.lang.Double annualSalary;

	private java.lang.Double hourlyRate;

	public Employee() {
	}

	public java.lang.Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(java.lang.Integer employeeId) {
		this.employeeId = employeeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getDateofHire() {
		return this.dateofHire;
	}

	public void setDateofHire(Date dateofHire) {
		this.dateofHire = dateofHire;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public ComputerRequest getRequestedMachine() {
		return this.requestedMachine;
	}

	public void setRequestedMachine(
			ComputerRequest requestedMachine) {
		this.requestedMachine = requestedMachine;
	}

	public ComputerRequest getAssignedMachine() {
		return this.assignedMachine;
	}

	public void setAssignedMachine(
			ComputerRequest assignedMachine) {
		this.assignedMachine = assignedMachine;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Double getAnnualSalary() {
		return this.annualSalary;
	}

	public void setAnnualSalary(java.lang.Double annualSalary) {
		this.annualSalary = annualSalary;
	}

	public Double getHourlyRate() {
		return this.hourlyRate;
	}

	public void setHourlyRate(Double hourlyRate) {
		this.hourlyRate = hourlyRate;
	}

	public Employee(Integer employeeId, String name,
			Date dateofHire, String role,
			String type, String location,
			Contact contact,
			ComputerRequest requestedMachine,
			ComputerRequest assignedMachine,
			String emailAddress, Double annualSalary,
			Double hourlyRate) {
		this.employeeId = employeeId;
		this.name = name;
		this.dateofHire = dateofHire;
		this.role = role;
		this.type = type;
		this.location = location;
		this.contact = contact;
		this.requestedMachine = requestedMachine;
		this.assignedMachine = assignedMachine;
		this.emailAddress = emailAddress;
		this.annualSalary = annualSalary;
		this.hourlyRate = hourlyRate;
	}

}